### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by derekwallace** [lord63/py-spin#4] opened 2016-01-02 18:12 UTC
Hi,
Python 3.5.0, using Cygwin or Cmd window.

Traceback (most recent call last):
  File "del1.py", line 16, in <module>
    print(u"\r{0}".format(spin.next()), end="")
  File "D:\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u280b' in position 1: character maps to <undefined>

Thx
Derek

**Comment by lord63** [comment] 2016-01-03 01:18
Unfortunately, my environment is linux mint 17.2, I use windows rarely, so I can't reproduce this problem and fix it. I haven't tested `py-spin` on windows yet. And the future support may won't consider the windows platform since I don't use it unless someone will kindly take this task.

**Comment by derekwallace** [comment] 2016-01-03 11:01
OK thx. Prob worth noting in release noted the os supported.
Derek.

**Comment by lord63** [comment] 2016-01-05 08:12
Yes,  in the [`setup.py`](https://github.com/lord63/py-spin/blob/master/setup.py#L30), I only guaranteed that the linux platform should be ok.

```
...
'Operating System :: POSIX',
'Operating System :: POSIX :: Linux',
...
```

Thanks for the report. Close it now.

**Closed as completed by lord63** 2016-01-05 08:12 UTC
